### ISSUE TITLE
No file named todo.db Error

### ISSUE THREAD

**Issue by MrBlueBirdv** [MrBlueBird2/to-do-list-flask#1]
When I tried running the file I get no file named todo.db Error, so @MrBlueBird2 can you tell me the solution?

**Comment by MrBlueBird2** [comment]
Hmm, That's easy just open your terminal and type
```
python
```
then type
```
from file-name import db
db.create_all()
```
Note: don't type file-name, type the name of the python file.

**Comment by MrBlueBirdv** [comment]
Thanx, That works for me
